version: "3.9"

networks:
  pg:
    name: pg
    driver: overlay
    attachable: true

volumes:
  pgdata:
    driver: local

services:
  postgis:
    image: $POSTGIS_IMAGE
    command: >-
      postgres
        -c autovacuum_max_workers=8
        -c autovacuum_vacuum_cost_delay=-1
        -c autovacuum=on
        -c fsync=on
        -c jit=on
        -c maintenance_work_mem=4GB
        -c max_connections=56
        -c max_locks_per_transaction=256
        -c max_parallel_maintenance_workers=4
        -c max_parallel_workers_per_gather=16
        -c max_parallel_workers=32
        -c max_prepared_transactions=100
        -c max_wal_senders=0
        -c max_wal_size=4GB
        -c max_worker_processes=16
        -c random_page_cost=3
        -c seq_page_cost=1
        -c shared_buffers=4GB
        -c track_counts=on
        -c wal_buffers=512MB
        -c wal_level=minimal
        -c wal_writer_delay=100ms
        -c work_mem=128MB
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.postgres == true
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: $CPUS
          memory: $MEMORY
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - $PORT:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - type: bind
        source: /dev/shm
        target: /dev/shm
    networks:
      - pg
