version: "3.8"

networks:
  pg:
    name: pg
    driver: overlay
    attachable: true

volumes:
  pgdata:
    driver: local

services:
  postgis:
    image: $POSTGIS_IMAGE
    command: >-
      postgres
        -c random_page_cost=3.5
        -c seq_page_cost=1
        -c shared_buffers=512MB
        -c work_mem=32MB
        -c maintenance_work_mem=128MB
        -c wal_buffers=4MB
        -c wal_level=minimal
        -c max_wal_senders=0
        -c fsync=on
        -c max_parallel_workers_per_gather=8
        -c max_parallel_maintenance_workers=4
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: $CPUS
          memory: $MEMORY
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - $PORT:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - pg
