version: '3.8'

networks:
  pg:
    name: $IMAGE_TAG
    driver: overlay
    attachable: true

volumes:
  pgdata:
    driver: local

services:
  postgis:
    image: $POSTGIS_IMAGE
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: '8'
          memory: 6G
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    networks:
      - $IMAGE_TAG