name: build@14

on:
  push:
    branches:
      - 14

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: SAEON/checkout@v2
        with:
          ref: 14

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/13
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}