name: deployment@13

on:
  push:
    branches:
      - 13

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}      

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: SAEON/checkout@v2
        with:
          ref: 13

      - name: Log in to the Container registry
        run: |
          echo hi