name: Deploy ghcr.io/saeon/postgis

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

env:
  BRANCH_REF: main

jobs:
  deploy:
    runs-on: github-runner.saeon.int
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_REF }}
        
      - name: (SCP) Copy Docker files to app server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOSTNAME }}
          username: ${{ secrets.DEPLOYMENT_HOST_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_HOST_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_HOST_SSH_PORT }}
          source: src/${{ github.event.inputs.tag }}/stack.yml
          target: postgis

      - name: (SSH) Deploy Docker stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOYMENT_HOSTNAME }}
          username: ${{ secrets.DEPLOYMENT_HOST_USERNAME }}
          password: ${{ secrets.DEPLOYMENT_HOST_PASSWORD }}
          port: ${{ secrets.DEPLOYMENT_HOST_SSH_PORT }}
          script: |
            echo "POSTGIS_IMAGE=ghcr.io/saeon/postgis:${{ github.event.inputs.tag }}" > /home/runner/postgis/src/${{ github.event.inputs.tag }}/stack.env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> /home/runner/postgis/src/${{ github.event.inputs.tag }}/stack.env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> /home/runner/postgis/src/${{ github.event.inputs.tag }}/stack.env
            sudo /opt/deploy-docker-stack.sh /home/runner/postgis/src/${{ github.event.inputs.tag }}/stack.yml /home/runner/postgis/src/${{ github.event.inputs.tag }}/stack.env postgis_${{ github.event.inputs.tag }}
