name: Deploy ghcr.io/saeon/postgis

on:
  workflow_dispatch:
    inputs:
      postgis_image_version:
        required: true
        type: string
      port:
        required: true
        default: 5432
        type: string
      stack_name:
        required: true
        type: string

env:
  BRANCH_REF: main
  HOST: ${{ secrets.DEPLOYMENT_HOSTNAME }}
  USER: ${{ secrets.DEPLOYMENT_HOST_USERNAME }}
  P: ${{ secrets.DEPLOYMENT_HOST_PASSWORD }}
  PORT: ${{ secrets.DEPLOYMENT_HOST_SSH_PORT }}

jobs:
  deploy:
    runs-on: github-runner.saeon.int
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_REF }}
        
      - name: (SCP) Copy Docker files to app server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PSWD }}
          port: ${{ env.PORT }}
          source: src/stack.yml
          target: postgis

      - name: (SSH) Deploy Docker stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PSWD }}
          port: ${{ env.PORT }}
          script: |
            echo "POSTGIS_IMAGE=ghcr.io/saeon/postgis:${{ github.event.inputs.postgis_image_version }}" > /home/${{ env.USER }}/postgis/src/stack.env
            echo "PORT=${{ github.event.inputs.port }}" >> /home/${{ env.USER }}/postgis/src/stack.env
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> /home/${{ env.USER }}/postgis/src/stack.env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> /home/${{ env.USER }}/postgis/src/stack.env
            sudo /opt/deploy-docker-stack.sh /home/${{ env.USER }}/postgis/src/stack.yml /home/${{ env.USER }}/postgis/src/stack.env ${{ github.event.inputs.stack_name }}
