name: Deploy ghcr.io/saeon/postgis

on:
  workflow_dispatch:
    inputs:
      postgis_image_version:
        required: true
        default: 15-3.3
        description: PostGIS image tag to use as base
        type: string
      port:
        required: true
        description: PostgreSQL port
        default: 5432
        type: string
      stack_name:
        required: true
        type: string
        description: Stack name
        default: postgis_v15

env:
  BRANCH_REF: main
  HOST: ${{ secrets.SWARM_HOSTNAME }} # Organization secret
  USER: ${{ secrets.SWARM_USERNAME }} # Organization secret
  PSWD: ${{ secrets.SWARM_PASSWORD }} # Organization secret
  PORT: ${{ secrets.SWARM_SSH_PORT }} # Organization secret
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }} # Repository secret
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }} # Repository secret
  CPUS: "16"
  MEMORY: 11G

jobs:
  deploy:
    runs-on: saeon
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: (SCP) Copy Docker files to app server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PSWD }}
          port: ${{ env.PORT }}
          source: src/stack.yml
          target: postgis

      - name: (SSH) Deploy Docker stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          password: ${{ env.PSWD }}
          port: ${{ env.PORT }}
          script: |
            echo "POSTGIS_IMAGE=ghcr.io/saeon/postgis:${{ github.event.inputs.postgis_image_version }}" > /home/${{ env.USER }}/postgis/src/stack.env
            echo "PORT=${{ github.event.inputs.port }}" >> /home/${{ env.USER }}/postgis/src/stack.env
            echo "POSTGRES_USER=${{ env.POSTGRES_USER }}" >> /home/${{ env.USER }}/postgis/src/stack.env
            echo "POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }}" >> /home/${{ env.USER }}/postgis/src/stack.env
            echo "CPUS=${{ env.CPUS }}" >> /home/${{ env.USER }}/postgis/src/stack.env
            echo "MEMORY=${{ env.MEMORY }}" >> /home/${{ env.USER }}/postgis/src/stack.env
            sudo /opt/deploy-docker-stack.sh /home/${{ env.USER }}/postgis/src/stack.yml /home/${{ env.USER }}/postgis/src/stack.env ${{ github.event.inputs.stack_name }}
